### ISSUE TITLE
unable to run code

### ISSUE THREAD

**Issue by simone-hochgreb** [sourcethemes/academic-admin#11]
unable to run -- some conflict with url parse after installation. 

baiao:academic_sh Simone$ pip install -U academic
Requirement already up-to-date: academic in /usr/local/lib/python2.7/site-packages (0.2.2)
Requirement already satisfied, skipping upgrade: bibtexparser in /usr/local/lib/python2.7/site-packages (from academic) (1.0.1)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python2.7/site-packages (from academic) (2.20.1)
Requirement already satisfied, skipping upgrade: toml in /usr/local/lib/python2.7/site-packages (from academic) (0.10.0)
Requirement already satisfied, skipping upgrade: pyparsing in /usr/local/lib/python2.7/site-packages (from bibtexparser->academic) (2.3.0)
Requirement already satisfied, skipping upgrade: future in /usr/local/lib/python2.7/site-packages (from bibtexparser->academic) (0.17.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests->academic) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests->academic) (2018.10.15)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests->academic) (1.24.1)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests->academic) (2.7)

baiao:academic_sh Simone$ academic academic import --bibtex ./content/articles/shpubs_2018.bib
Traceback (most recent call last):
  File "/usr/local/bin/academic", line 7, in <module>
    from academic.cli import main
  File "/usr/local/lib/python2.7/site-packages/academic/cli.py", line 11, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
baiao:academic_sh Simone$ pip install urlparse
Collecting urlparse
  Could not find a version that satisfies the requirement urlparse (from versions: )
No matching distribution found for urlparse

**Comment by simone-hochgreb** [comment]
Thanks. Installed. New problem: 

academic import --bibtex ./content/publication/articles/shpubs_2018.bib 

leads to: 

Traceback (most recent call last):
  File "/usr/local/bin/academic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/academic/cli.py", line 76, in main
    import_bibtex(args.bibtex, pub_dir=args.publication_dir, featured=args.featured, overwrite=args.overwrite)
  File "/usr/local/lib/python3.7/site-packages/academic/cli.py", line 88, in import_bibtex
    with open(bibtex, mode='rb', encoding='utf-8') as bibtex_file:
ValueError: binary mode doesn't take an encoding argument

**Comment by simone-hochgreb** [comment]
Thanks for the quick return. Same problem after cloning: 

baiao:hugo Simone$ git clone https://github.com/sourcethemes/academic-kickstart.git acad2
Cloning into 'acad2'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 214 (delta 0), reused 3 (delta 0), pack-reused 209
Receiving objects: 100% (214/214), 57.71 KiB | 0 bytes/s, done.
Resolving deltas: 100% (70/70), done.
Checking connectivity... done.
baiao:hugo Simone$ cd acad2
baiao:acad2 Simone$ ls
LICENSE.md		config.toml		netlify.toml		themes
README.md		content			static			update_academic.sh
baiao:acad2 Simone$ academic import --bibtex ./content/publication/articles/shpubs_2018.bib
Traceback (most recent call last):
  File "/usr/local/bin/academic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/academic/cli.py", line 76, in main
    import_bibtex(args.bibtex, pub_dir=args.publication_dir, featured=args.featured, overwrite=args.overwrite)
  File "/usr/local/lib/python3.7/site-packages/academic/cli.py", line 88, in import_bibtex
    with open(bibtex, mode='rb', encoding='utf-8') as bibtex_file:
ValueError: binary mode doesn't take an encoding argument

**Comment by gcushen** [comment]
I was referring to updating Academic Admin (this repo) to v0.2.4, not Academic Kickstart.
