### ISSUE TITLE
import --assets is broken

### ISSUE THREAD

**Issue by jeroenh** [sourcethemes/academic-admin#12]
```
ᐅ academic import --assets
Downloading jquery.min.js from https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js...
Downloading bootstrap.min.js from https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js...
Downloading highlight.min.js from https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js...
Downloading MathJax.js from https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_CHTML-full...
Downloading isotope.pkgd.min.js from https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js...
Downloading imagesloaded.pkgd.min.js from https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js...
Downloading autotrack.js from https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js...
Downloading gmaps.min.js from https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js...
Downloading leaflet.js from https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.js...
Downloading jquery.fancybox.min.js from https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js...
Downloading fuse.min.js from https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js...
Downloading jquery.mark.min.js from https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js...
Downloading instantsearch.min.js from https://cdnjs.cloudflare.com/ajax/libs/instantsearch.js/2.10.2/instantsearch.min.js...
Downloading anchor.min.js from https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js...
Merging JS assets into static/js/vendor/main.min.js
Traceback (most recent call last):
  File "/usr/local/bin/academic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/academic/cli.py", line 75, in main
    import_assets()
  File "/usr/local/lib/python3.6/site-packages/academic/cli.py", line 282, in import_assets
    merge_files(js_files, JS_FILENAME)
  File "/usr/local/lib/python3.6/site-packages/academic/cli.py", line 323, in merge_files
    with open(destination, 'w', encoding='utf-8') as f:
IsADirectoryError: [Errno 21] Is a directory: 'static/js/vendor/main.min.js'
```

**Comment by gcushen** [comment]
Thanks for reporting this bug. It has been fixed in v0.2.5, now on Pypi.
